name: Initial Pipeline

on:
  push:
    branches:
      - main
  # Allows manual running from github
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build & Test Python App
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.10'

    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v4

    - name: 2. Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 3. Install Dependencies
      run: pip install -r requirements.txt

    - name: Linting
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Unit Tests
      run: |
        pip install pytest
        pytest
